#This docker-compose file is used for local development and testing only !
#The application service depends on the database and cache services being healthy
#before starting.
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: shortlink
      POSTGRES_USER: shortlink
      POSTGRES_PASSWORD: shortlink
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortlink -d shortlink"]
      interval: 3s
      timeout: 3s
      retries: 15

  flyway:
    image: flyway/flyway:11-alpine
    command: -connectRetries=30 migrate
    volumes:
      - ./migrations:/flyway/sql:ro
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/shortlink
      FLYWAY_USER: shortlink
      FLYWAY_PASSWORD: shortlink
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ..
      dockerfile: link-api/Dockerfile
    image: link-api:1.0
    container_name: link-api
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/shortlink
      DB_USER: shortlink
      DB_PASSWORD: shortlink
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SHORT_BASE_URL: http://localhost:8081
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    restart: unless-stopped


volumes:
  pgdata:
